# Setup
title: David Gillhespy
url: http://davidgillhespy.com
paginate: 5
gems: ["jekyll-paginate","jekyll-crosspost-to-medium"]

# About/contact
author:
  name: Dave Gillhespy
  url: https://davidgillhespy.com
  email: yodasw16@gmail.com

# Custom vars
github:
  repo: https://github.com/yodasw16/yodasw16.github.io

# Exclude
exclude: [node_modules, sass, package.json, gulpfile.js]

jekyll-crosspost_to_medium:
  text: '<p>This article was originally posted on <a href="{{ url }}" rel="canonical">davidgillhespy.com</a>.</p>'
