name: davidgillhespy.com
description: "The blog of Dave Gillhespy: web developer and pretty awesome guy"
url: http://davidgillhespy.com
markdown: redcarpet
highlighter: pygments
paginate: 5
exclude: [sass, node_modules, Gemfile, Gemfile.lock, Gruntfile.js, package.json]
